[dev] - Fixed value to be top aligned vertically in the input field box when used as multiline.
saddlebackdev/hc-mobile-app-ui pull request #121
Opened 2022-07-27 20:41 UTC by ardneved

2022-07-27 22:03 UTC, raoufr requested changes
looking good, we are just missing the change log entry for this update. Please let me know if you need guidance to add it. Thanks

2022-07-27 22:03 UTC, raoufr commented on src/modules/text-input/text-input.tsx
> +
can we remove the empty line?

2022-07-28 03:44 UTC, ajaybushel commented
Do we really need to make changes in the styles? I think this should work even if we just pass the `multiline` prop to the component. 🤔

2022-07-28 05:10 UTC, ardneved commented on src/modules/text-input/text-input.tsx
> +
sure, it's done

2022-07-28 05:13 UTC, ardneved commented
> Do we really need to make changes in the styles? I think this should work even if we just pass the `multiline` prop to the component. 🤔

Yes we do.
please see the [reference](https://reactnative.dev/docs/0.67/textinput#multiline)

2022-07-28 05:15 UTC, ardneved commented
> looking good, we are just missing the change log entry for this update. Please let me know if you need guidance to add it. Thanks

@raoufr thank you, yes some guidance for change log entry would be really helpful

2022-07-28 16:03 UTC, raoufr approved these changes
Please add a changelog entry for this fix and we should good to merge

2022-07-28 16:30 UTC, ardneved commented
> Please add a changelog entry for this fix and we should good to merge

@raoufr thank you,
change log updated

2022-07-28 18:52 UTC, KacosPro approved these changes
LGTM

2022-08-02 17:23 UTC, raoufr commented
Thank you @ardneved  for the updates. We are going to go ahead and merge this one.

2022-08-02 17:27 UTC, merged