[dev] - No PBI - lower prompts elements and button visibility in appium android
saddlebackdev/hc-mobile-app-ui pull request #89
Opened 2022-04-17 08:36 UTC by pakkibokati2012

2022-04-19 03:35 UTC, ajaybushel approved these changes
Looks good to me. However, couldn't we use `test id` instead of adding `accessibility label`s?

2022-04-19 05:59 UTC, pakkibokati2012 commented
> 



> Looks good to me. However, couldn't we use `test id` instead of adding `accessibility label`s?
![Screen Shot 2022-04-17 at 14 02 56](https://user-images.githubusercontent.com/34542543/163934189-56956505-7c91-47a7-a7fc-62acd0055816.png)
The testing automation team has explicitly asked for the` accessiblity id` field to show up on appium inspector. This cannot be achieved without setting the` accessiblity label` prop.

2022-04-19 10:51 UTC, ajaybushel commented
Understood. Thanks @pakkibokati2012

2022-04-19 22:07 UTC, mdjacobs commented on src/modules/button/button.tsx
> +          accessibilityLabel="button-label"
My only concern is that if there are say 5 buttons on the page, automation will not know which one to pick.

2022-04-19 22:12 UTC, mdjacobs requested changes
If we can make some changes as best as possible to include some parameters to allow automation to target these elements in both buttons and lower prompts.

2022-04-19 22:12 UTC, mdjacobs commented
@pakkibokati2012 can you do some adjustments to help target these elements better?

2022-04-28 20:17 UTC, raoufr approved these changes
Looking good to me

2022-05-03 23:34 UTC, merged