Add Tab component
saddlebackdev/hc-mobile-app-ui pull request #96
Opened 2022-05-11 13:40 UTC by krishnakant-technossus

**Note:**
**- Slated for v0.0.34**
**- This PR is derived from PR** #95 

Tab component.

Here's how it looks:
![Screenshot_20220516-152157_Mau](https://user-images.githubusercontent.com/103095250/168567106-4398f85e-2cb8-4c7d-b904-598b16407a2e.jpg)

2022-05-12 04:38 UTC, ajaybushel approved these changes

2022-05-12 04:38 UTC, ajaybushel commented
Only suggestion is, do we need an inverse variant of this component?

2022-05-12 04:44 UTC, ajaybushel requested changes
I don't think we should be calling this component UpperTabs. Please rename this to "Tabs".

2022-05-12 07:20 UTC, krishnakant-technossus commented
> Only suggestion is, do we need an inverse variant of this component?

Well I don't think because I checked in sketch design and there is no tabs shown over the dark background. only I can see the tabs over the light background. But if you say and it may require in future then we can add inverse mode too.

2022-05-12 07:21 UTC, krishnakant-technossus commented
> I don't think we should be calling this component UpperTabs. Please rename this to "Tabs".

Okay I will do this.

2022-05-12 17:11 UTC, stevekardian approved these changes

2022-05-12 17:12 UTC, stevekardian approved these changes

2022-05-15 18:58 UTC, raoufr approved these changes
Looking good to me. A couple of unblocking comments for discussion and future follow up PR potentially.

2022-05-15 18:58 UTC, raoufr commented on App.tsx
> +
I know this was not introduced by this PR, but the url in line #296 seems wrong to me. 
Any ideas @ajaybushel @mdjacobs @bittu1028?
I would think we do not want to hard code an external URL and if we have to have this probably refer to a local image.

2022-05-15 18:58 UTC, raoufr commented on src/modules/tabs/tabs.tsx
> +import {IProps, IStyledText, IStyledTouchable, ITab} from './tabs.types';
@ajaybushel I think we should follow this sub extension for interfaces as well. But let's discuss and sync up on the convention that should be followed across the board.

2022-05-15 18:58 UTC, raoufr commented
@krishnakant-technossus please address @ajaybushel 's request(s) for changes and also resolve the conflict above before we can merge. Thank you.

2022-05-15 19:00 UTC, raoufr commented
@krishnakant-technossus  also please add a brief description in the change log to what has been added with this PR. thanks

2022-05-16 23:50 UTC, merged